apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: volume-permissions-container-injector-webhook-cfg
  labels:
    app: volume-permissions-container-injector
webhooks:
- name: volume-permissions-container-injector.malston.me
  clientConfig:
    service:
      name: vpci-webhook-svc
      namespace: volume-permissions-container-injector
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      volume-permissions-container-injection: enabled
