apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpci-webhook-mutatingwebhookconfiguration-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpci-webhook-mutatingwebhookconfiguration-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: volume-permissions-container-injector
roleRef:
  kind: ClusterRole
  name: vpci-webhook-mutatingwebhookconfiguration-admin
  apiGroup: rbac.authorization.k8s.io
