apiVersion: v1
kind: Service
metadata:
  name: vpci-webhook-svc
  namespace: volume-permissions-container-injector
  labels:
    app: volume-permissions-container-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: volume-permissions-container-injector
