apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-minio
  namespace: sentry-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotsadm-minio
  serviceName: ""
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: kotsadm-minio,minio-config-dir
      labels:
        app: kotsadm-minio
        kots.io/backup: velero
        kots.io/kotsadm: "true"
    spec:
      initContainers:
      - command:
        - /bin/bash
        - -ec
        - |
          chown -R 1001:1001 /export
        image: docker.io/bitnami/bitnami-shell:10
        imagePullPolicy: Always
        name: volume-permissions
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /export
          name: kotsadm-minio
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-bg6bv
          readOnly: true
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -C /home/minio/.minio/ --quiet server
          /export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: kotsadm-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: kotsadm-minio
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_UPDATE
          value: "off"
        image: minio/minio:RELEASE.2021-05-11T23-27-41Z
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: service
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: kotsadm-minio
        ports:
        - containerPort: 9000
          name: service
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/ready
            port: service
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - mountPath: /export
          name: kotsadm-minio
        - mountPath: /home/minio/.minio/
          name: minio-config-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
      - name: kotsadm-minio
        persistentVolumeClaim:
          claimName: kotsadm-minio
      - emptyDir: {}
        name: minio-config-dir
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        kots.io/backup: velero
        kots.io/kotsadm: "true"
      name: kotsadm-minio
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
      volumeMode: Filesystem
