apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kots.io/app-slug: sentry-pro
    kots.io/hook-delete-policy: hook-succeeded, hook-failed
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"kots.io/app-slug":"sentry-pro","kots.io/hook-delete-policy":"hook-succeeded, hook-failed"},"labels":{"app":"sentry","kots.io/app-slug":"sentry-pro","kots.io/backup":"velero"},"name":"sentry-db-init","namespace":"sentry-pro"},"spec":{"template":{"metadata":{"annotations":{"kots.io/app-slug":"sentry-pro"},"labels":{"app":"sentry","component":"sentry","kots.io/app-slug":"sentry-pro","kots.io/backup":"velero"},"name":"sentry-db-init"},"spec":{"containers":[{"command":["sentry","upgrade","--noinput"],"env":[{"name":"SENTRY_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"sentry-secret","name":"sentry"}}},{"name":"SENTRY_DB_USER","value":"sentry"},{"name":"SENTRY_DB_NAME","value":"sentry"},{"name":"SENTRY_DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"postgres-password","name":"sentry-postgresql"}}},{"name":"SENTRY_POSTGRES_HOST","value":"sentry-postgresql"},{"name":"SENTRY_POSTGRES_PORT","value":"5432"},{"name":"SENTRY_REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"sentry-redis"}}},{"name":"SENTRY_REDIS_HOST","value":"sentry-redis-master"},{"name":"SENTRY_REDIS_PORT","value":"6379"},{"name":"SENTRY_EMAIL_HOST","value":""},{"name":"SENTRY_EMAIL_PORT","value":""},{"name":"SENTRY_EMAIL_USER","value":""},{"name":"SENTRY_EMAIL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"smtp-password","name":"sentry"}}},{"name":"SENTRY_EMAIL_USE_TLS","value":"false"},{"name":"SENTRY_SERVER_EMAIL","value":"sentry@sentry.local"}],"image":"sentry:9.1.1","name":"db-init-job","volumeMounts":[{"mountPath":"/etc/sentry","name":"config","readOnly":true}]}],"restartPolicy":"Never","volumes":[{"configMap":{"name":"sentry"},"name":"config"}]}}}}
  creationTimestamp: "2021-05-24T15:02:48Z"
  labels:
    app: sentry
    kots.io/app-slug: sentry-pro
    kots.io/backup: velero
  name: sentry-db-init
  namespace: sentry-pro
  resourceVersion: "25021644"
  uid: 20422073-ffcd-4a16-850b-ab720b09dd6c
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 20422073-ffcd-4a16-850b-ab720b09dd6c
  template:
    metadata:
      annotations:
        kots.io/app-slug: sentry-pro
      creationTimestamp: null
      labels:
        app: sentry
        component: sentry
        controller-uid: 20422073-ffcd-4a16-850b-ab720b09dd6c
        job-name: sentry-db-init
        kots.io/app-slug: sentry-pro
        kots.io/backup: velero
      name: sentry-db-init
    spec:
      containers:
      - command:
        - sentry
        - upgrade
        - --noinput
        env:
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: sentry-secret
              name: sentry
        - name: SENTRY_DB_USER
          value: sentry
        - name: SENTRY_DB_NAME
          value: sentry
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: sentry-postgresql
        - name: SENTRY_POSTGRES_HOST
          value: sentry-postgresql
        - name: SENTRY_POSTGRES_PORT
          value: "5432"
        - name: SENTRY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: sentry-redis
        - name: SENTRY_REDIS_HOST
          value: sentry-redis-master
        - name: SENTRY_REDIS_PORT
          value: "6379"
        - name: SENTRY_EMAIL_HOST
        - name: SENTRY_EMAIL_PORT
        - name: SENTRY_EMAIL_USER
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp-password
              name: sentry
        - name: SENTRY_EMAIL_USE_TLS
          value: "false"
        - name: SENTRY_SERVER_EMAIL
          value: sentry@sentry.local
        image: sentry:9.1.1
        imagePullPolicy: IfNotPresent
        name: db-init-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: sentry
        name: config
status:
  active: 1
  failed: 6
  startTime: "2021-05-24T15:02:48Z"
