apiVersion: v1
kind: Pod
metadata:
  annotations:
    kots.io/app-slug: sentry-pro
    kubernetes.io/psp: sentry-pro-psp
  creationTimestamp: "2021-05-21T23:36:56Z"
  generateName: sentry-redis-master-
  labels:
    app: redis
    component: sentry
    controller-revision-hash: sentry-redis-master-7b9d478c64
    kots.io/app-slug: sentry-pro
    kots.io/backup: velero
    role: master
    statefulset.kubernetes.io/pod-name: sentry-redis-master-0
  name: sentry-redis-master-0
  namespace: sentry-pro
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sentry-redis-master
    uid: 23b8cc1e-debe-4feb-b310-29d63eab7afe
  resourceVersion: "17733872"
  uid: ab616fea-c9a5-4bf7-b773-07e52ccb7272
spec:
  containers:
  - env:
    - name: REDIS_REPLICATION_MODE
      value: master
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: redis-password
          name: sentry-redis
    - name: REDIS_DISABLE_COMMANDS
      value: FLUSHDB,FLUSHALL
    image: docker.io/bitnami/redis:4.0.11-debian-9
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - redis-cli
        - ping
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: sentry-redis
    ports:
    - containerPort: 6379
      name: redis
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - redis-cli
        - ping
      failureThreshold: 5
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/redis/data
      name: redis-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-bg6bv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sentry-redis-master-0
  imagePullSecrets:
  - name: index.docker.io
  nodeName: dev-cluster-workers-j7tc7-8546bb84bf-m26hn
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount: default
  serviceAccountName: default
  subdomain: redis-master
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: redis-data-sentry-redis-master-0
  - name: default-token-bg6bv
    secret:
      defaultMode: 420
      secretName: default-token-bg6bv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T23:36:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T23:36:56Z"
    message: 'containers with unready status: [sentry-redis]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T23:36:56Z"
    message: 'containers with unready status: [sentry-redis]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T23:36:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://cf2eba3c78fe163533a26695d2472fb911507039011cd6b643774e2395b00251
    image: docker.io/bitnami/redis:4.0.11-debian-9
    imageID: docker.io/bitnami/redis@sha256:8b378350e114597e50bd09317a0bc096f835d368cae8587f36c4d626ed834d13
    lastState:
      terminated:
        containerID: containerd://cf2eba3c78fe163533a26695d2472fb911507039011cd6b643774e2395b00251
        exitCode: 1
        finishedAt: "2021-05-21T23:37:03Z"
        reason: Error
        startedAt: "2021-05-21T23:37:03Z"
    name: sentry-redis
    ready: false
    restartCount: 1
    started: false
    state:
      waiting:
        message: back-off 10s restarting failed container=sentry-redis pod=sentry-redis-master-0_sentry-pro(ab616fea-c9a5-4bf7-b773-07e52ccb7272)
        reason: CrashLoopBackOff
  hostIP: 192.168.12.28
  phase: Running
  podIP: 100.96.5.129
  podIPs:
  - ip: 100.96.5.129
  qosClass: BestEffort
  startTime: "2021-05-21T23:36:56Z"
