apiVersion: v1
kind: Pod
metadata:
  name: spring-petclinic-image-build-1-hxszd-build-pod
  namespace: kpack-tutorial
spec:
  containers:
  - name: completion
    image: gcr.io/cf-build-service-public/kpack/completion@sha256:7b8b829ee21f6009ea9b580cad86fb2f74f28d2aa34676d4a130fb62b9fc9893
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: registry-credentials
  initContainers:
  - args:
    - -dockerconfig=registry-credentials
    env:
    - name: GIT_URL
      value: https://github.com/malston/spring-petclinic
    - name: GIT_REVISION
      value: 8239cd9361836385ba9415fb96b6868201a603a2
    - name: PLATFORM_ENV_VARS
      value: "null"
    - name: IMAGE_TAG
      value: harbor.markalston.net/tanzu/spring-petclinic
    - name: RUN_IMAGE
      value: heroku/pack:20
    - name: DNS_PROBE_HOSTNAME
      value: harbor.markalston.net
    - name: BUILD_CHANGES
      value: '[{"reason":"CONFIG","old":{"resources":{},"source":{}},"new":{"resources":{},"source":{"git":{"url":"https://github.com/malston/spring-petclinic","revision":"8239cd9361836385ba9415fb96b6868201a603a2"}}}}]'
    image: gcr.io/cf-build-service-public/kpack/build-init@sha256:94cdd9223310c2bbc6b9f10d17f754337d782f32ac1cd7de58d3e78746d5ab7c
    imagePullPolicy: IfNotPresent
    name: prepare
    volumeMounts:
    - mountPath: /var/build-secrets/registry-credentials
      name: secret-volume-registry-credentials
    - mountPath: /builderPullSecrets
      name: builder-pull-secrets-dir
      readOnly: true
    - mountPath: /imagePullSecrets
      name: image-pull-secrets-dir
      readOnly: true
    - mountPath: /platform
      name: platform-dir
    - mountPath: /workspace
      name: workspace-dir
    - mountPath: /builder/home
      name: home-dir
    - mountPath: /projectMetadata
      name: layers-dir
    workingDir: /workspace
  - args:
    - -app=/workspace
    - -group=/layers/group.toml
    - -plan=/layers/plan.toml
    command:
    - /cnb/lifecycle/detector
    env:
    - name: CNB_PLATFORM_API
      value: "0.5"
    image: harbor.markalston.net/kpack/heroku-builder@sha256:04a70d51b27825468347a19e992e000f80e18177973126f48cb828de7c24f138
    imagePullPolicy: IfNotPresent
    name: detect
    volumeMounts:
    - mountPath: /layers
      name: layers-dir
    - mountPath: /platform
      name: platform-dir
    - mountPath: /workspace
      name: workspace-dir
  - args:
    - -layers=/layers
    - -group=/layers/group.toml
    - -analyzed=/layers/analyzed.toml
    - -cache-dir=/cache
    - harbor.markalston.net/tanzu/spring-petclinic
    command:
    - /cnb/lifecycle/analyzer
    env:
    - name: HOME
      value: /builder/home
    - name: CNB_PLATFORM_API
      value: "0.5"
    image: harbor.markalston.net/kpack/heroku-builder@sha256:04a70d51b27825468347a19e992e000f80e18177973126f48cb828de7c24f138
    imagePullPolicy: IfNotPresent
    name: analyze
    volumeMounts:
    - mountPath: /layers
      name: layers-dir
    - mountPath: /workspace
      name: workspace-dir
    - mountPath: /builder/home
      name: home-dir
    - mountPath: /cache
      name: cache-dir
  - args:
    - -group=/layers/group.toml
    - -layers=/layers
    - -cache-dir=/cache
    command:
    - /cnb/lifecycle/restorer
    env:
    - name: CNB_PLATFORM_API
      value: "0.5"
    image: harbor.markalston.net/kpack/heroku-builder@sha256:04a70d51b27825468347a19e992e000f80e18177973126f48cb828de7c24f138
    imagePullPolicy: IfNotPresent
    name: restore
    volumeMounts:
    - mountPath: /layers
      name: layers-dir
    - mountPath: /cache
      name: cache-dir
  - args:
    - -layers=/layers
    - -app=/workspace
    - -group=/layers/group.toml
    - -plan=/layers/plan.toml
    command:
    - /cnb/lifecycle/builder
    env:
    - name: CNB_PLATFORM_API
      value: "0.5"
    image: harbor.markalston.net/kpack/heroku-builder@sha256:04a70d51b27825468347a19e992e000f80e18177973126f48cb828de7c24f138
    imagePullPolicy: IfNotPresent
    name: build
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: layers-dir
    - mountPath: /platform
      name: platform-dir
    - mountPath: /workspace
      name: workspace-dir
  - args:
    - -layers=/layers
    - -app=/workspace
    - -group=/layers/group.toml
    - -analyzed=/layers/analyzed.toml
    - -cache-dir=/cache
    - -project-metadata=/layers/project-metadata.toml
    - -report=/var/report/report.toml
    - -process-type=web
    - harbor.markalston.net/tanzu/spring-petclinic
    - harbor.markalston.net/tanzu/spring-petclinic:b1.20210524.171408
    command:
    - /cnb/lifecycle/exporter
    env:
    - name: HOME
      value: /builder/home
    - name: CNB_PLATFORM_API
      value: "0.5"
    image: harbor.markalston.net/kpack/heroku-builder@sha256:04a70d51b27825468347a19e992e000f80e18177973126f48cb828de7c24f138
    imagePullPolicy: IfNotPresent
    name: export
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: layers-dir
    - mountPath: /workspace
      name: workspace-dir
    - mountPath: /builder/home
      name: home-dir
    - mountPath: /cache
      name: cache-dir
    - mountPath: /var/report
      name: report-dir
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  serviceAccount: service-account
  serviceAccountName: service-account
  terminationGracePeriodSeconds: 30
  volumes:
  - name: secret-volume-registry-credentials
    secret:
      defaultMode: 420
      secretName: registry-credentials
  - name: cache-dir
    persistentVolumeClaim:
      claimName: spring-petclinic-image-cache
  - emptyDir: {}
    name: layers-dir
  - emptyDir: {}
    name: home-dir
  - emptyDir: {}
    name: workspace-dir
  - emptyDir: {}
    name: platform-dir
  - emptyDir: {}
    name: report-dir
  - emptyDir: {}
    name: network-wait-launcher-dir
  - emptyDir: {}
    name: image-pull-secrets-dir
  - emptyDir: {}
    name: builder-pull-secrets-dir
  - emptyDir: {}
    name: notary-dir
